# Generated by Django 4.2.13 on 2025-06-26 04:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "course_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="课程进度ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        help_text="课程所属学科名称",
                        max_length=100,
                        verbose_name="学科名称",
                    ),
                ),
                (
                    "content_id",
                    models.UUIDField(
                        help_text="关联的课程内容标识符", verbose_name="课程内容ID"
                    ),
                ),
                (
                    "user_experience",
                    models.TextField(
                        blank=True,
                        help_text="用户自我描述的相关经验和背景",
                        verbose_name="用户经验描述",
                    ),
                ),
                (
                    "proficiency_level",
                    models.IntegerField(
                        choices=[
                            (0, "初学者"),
                            (25, "基础"),
                            (50, "中级"),
                            (75, "高级"),
                            (100, "专家"),
                        ],
                        default=0,
                        help_text="用户对该学科的掌握程度（0-100）",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="掌握程度",
                    ),
                ),
                (
                    "learning_hour_week",
                    models.IntegerField(
                        default=0,
                        help_text="最近一周的学习时长（小时）",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="本周学习时长",
                    ),
                ),
                (
                    "learning_hour_total",
                    models.IntegerField(
                        default=0,
                        help_text="总计学习时长（小时）",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="累计学习时长",
                    ),
                ),
                (
                    "est_finish_hour",
                    models.IntegerField(
                        blank=True,
                        help_text="预计完成课程所需时长（小时）",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="预计完成时长",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (1, "极易"),
                            (2, "简单"),
                            (3, "容易"),
                            (4, "适中偏易"),
                            (5, "适中"),
                            (6, "适中偏难"),
                            (7, "困难"),
                            (8, "很难"),
                            (9, "极难"),
                            (10, "专家级"),
                        ],
                        help_text="课程难度评分（1-10）",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="课程难度",
                    ),
                ),
                (
                    "feedback",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="用户对课程和内容的反馈信息",
                        verbose_name="用户反馈",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程进度",
                "verbose_name_plural": "课程进度",
                "db_table": "course_progress",
                "ordering": ["-updated_at"],
                "unique_together": {("user_uuid", "content_id")},
            },
        ),
    ]
