# Generated by Django 4.2.13 on 2025-06-26 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='内容唯一标识符')),
                ('outline', models.JSONField(default=dict, help_text='课程大纲，结构化 JSON 格式', verbose_name='课程大纲')),
                ('chapters', models.JSONField(default=list, help_text='每一章的内容，数组格式，如：[{ "title": "Intro", "text": "..." }, ...]', verbose_name='章节内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程内容',
                'verbose_name_plural': '课程内容',
                'db_table': 'course_content',
                'ordering': ['-updated_at'],
            },
        ),
    ]
