# Generated by Django 4.2.13 on 2025-06-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_add_course_content"),
    ]

    operations = [
        # 1. 重命名表：course_content -> course_contents
        migrations.RunSQL(
            "ALTER TABLE course_content RENAME TO course_contents;",
            reverse_sql="ALTER TABLE course_contents RENAME TO course_content;"
        ),
        
        # 2. 添加新的外键字段 content_id
        migrations.AddField(
            model_name='courseprogress',
            name='content_id',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='progress_records',
                to='courses.coursecontent',
                verbose_name='课程内容',
                help_text='关联的课程内容',
                db_column='content_id'
            ),
        ),
        
        # 3. 更新外键引用
        migrations.RunSQL(
            "UPDATE course_progress SET content_id = course_content_id;",
            reverse_sql="UPDATE course_progress SET course_content_id = content_id;"
        ),
        
        # 4. 删除旧字段
        migrations.RemoveField(
            model_name='courseprogress',
            name='course_content',
        ),
        
        # 5. 更新约束
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('user_uuid', 'content_id')},
        ),
    ]by Django 4.2.13 on 2025-06-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_add_course_content"),
    ]

    operations = []
