# Generated by Django 4.2.13 on 2025-06-26 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否激活")),
                ("title", models.CharField(max_length=200, verbose_name="目标标题")),
                ("description", models.TextField(verbose_name="目标描述")),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("skill", "技能目标"),
                            ("knowledge", "知识目标"),
                            ("certification", "认证目标"),
                            ("project", "项目目标"),
                        ],
                        default="skill",
                        max_length=20,
                        verbose_name="目标类型",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "初级"),
                            ("intermediate", "中级"),
                            ("advanced", "高级"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "estimated_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="预估学习时长(小时)"
                    ),
                ),
            ],
            options={
                "verbose_name": "学习目标",
                "verbose_name_plural": "学习目标",
                "db_table": "learning_goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否激活")),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200, verbose_name="计划标题")),
                ("description", models.TextField(blank=True, verbose_name="计划描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "进行中"),
                            ("completed", "已完成"),
                            ("paused", "已暂停"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "target_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="目标结束日期"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="实际结束日期"
                    ),
                ),
                (
                    "total_estimated_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="总预估时长(小时)"
                    ),
                ),
                (
                    "ai_recommendations",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="AI推荐内容"
                    ),
                ),
            ],
            options={
                "verbose_name": "学习计划",
                "verbose_name_plural": "学习计划",
                "db_table": "learning_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPlanGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否激活")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("skipped", "已跳过"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="顺序")),
                (
                    "actual_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="实际学习时长(小时)"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="学习笔记")),
                (
                    "learning_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning_plans.learninggoal",
                        verbose_name="学习目标",
                    ),
                ),
                (
                    "learning_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning_plans.learningplan",
                        verbose_name="学习计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习计划目标",
                "verbose_name_plural": "学习计划目标",
                "db_table": "learning_plan_goals",
                "ordering": ["order", "created_at"],
                "unique_together": {("learning_plan", "learning_goal")},
            },
        ),
        migrations.AddField(
            model_name="learningplan",
            name="goals",
            field=models.ManyToManyField(
                related_name="learning_plans",
                through="learning_plans.LearningPlanGoal",
                to="learning_plans.learninggoal",
                verbose_name="学习目标",
            ),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否激活")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="学习时长(分钟)"
                    ),
                ),
                (
                    "content_covered",
                    models.TextField(blank=True, verbose_name="学习内容"),
                ),
                (
                    "effectiveness_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="学习效果评分(1-5)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="学习笔记")),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="learning_plans.learninggoal",
                        verbose_name="学习目标",
                    ),
                ),
                (
                    "learning_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="learning_plans.learningplan",
                        verbose_name="学习计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习会话",
                "verbose_name_plural": "学习会话",
                "db_table": "study_sessions",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["learning_plan", "start_time"],
                        name="study_sessi_learnin_0fe729_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="learningplan",
            index=models.Index(
                fields=["user", "status"], name="learning_pl_user_id_3475e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningplan",
            index=models.Index(
                fields=["start_date"], name="learning_pl_start_d_1b9558_idx"
            ),
        ),
    ]
