# Generated by Django 4.2.13 on 2025-06-26 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning_plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="effectiveness_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "很差"),
                    (2, "较差"),
                    (3, "一般"),
                    (4, "良好"),
                    (5, "优秀"),
                ],
                null=True,
                verbose_name="学习效果评分(1-5)",
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_sessions",
                to="learning_plans.learninggoal",
                verbose_name="学习目标",
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="当前是否在进行中"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="learning_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_sessions",
                to="learning_plans.learningplan",
                verbose_name="学习计划",
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["goal", "start_time"], name="study_sessi_goal_id_5b3287_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["is_active", "start_time"],
                name="study_sessi_is_acti_5f0211_idx",
            ),
        ),
    ]
