# Generated by Django 4.2.13 on 2025-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_plans", "0002_alter_studysession_effectiveness_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningplan",
            name="goals",
        ),
        migrations.RemoveField(
            model_name="learningplan",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="learningplangoal",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="learningplangoal",
            name="learning_goal",
        ),
        migrations.RemoveField(
            model_name="learningplangoal",
            name="learning_plan",
        ),
        migrations.RemoveIndex(
            model_name="studysession",
            name="study_sessi_learnin_0fe729_idx",
        ),
        migrations.RemoveIndex(
            model_name="studysession",
            name="study_sessi_goal_id_5b3287_idx",
        ),
        migrations.RemoveField(
            model_name="studysession",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="studysession",
            name="learning_plan",
        ),
        migrations.AddField(
            model_name="studysession",
            name="goal_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="学习目标ID"),
        ),
        migrations.AddField(
            model_name="studysession",
            name="learning_plan_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="学习计划ID"),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["goal_id", "start_time"], name="study_sessi_goal_id_5b3287_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["learning_plan_id", "start_time"],
                name="study_sessi_learnin_0fe729_idx",
            ),
        ),
        migrations.DeleteModel(
            name="LearningGoal",
        ),
        migrations.DeleteModel(
            name="LearningPlan",
        ),
        migrations.DeleteModel(
            name="LearningPlanGoal",
        ),
    ]
