# Generated by Django 4.2.13 on 2025-06-26 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning_plans", "0003_remove_unused_models"),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='study_sessions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='用户',
                null=True,  # Allow null temporarily
                blank=True
            ),
        ),
    ]
