# Generated by Django 4.2.13 on 2025-06-26 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning_plans", "0004_auto_20250626_1458"),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='study_sessions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='用户',
                help_text='学习会话所属用户'
            ),
        ),
    ]
