# Generated by Django 4.2.13 on 2025-06-26 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user_uuid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "preferred_pace",
                    models.CharField(
                        choices=[
                            ("slow", "慢节奏"),
                            ("normal", "正常节奏"),
                            ("fast", "快节奏"),
                            ("flexible", "灵活调整"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="偏好学习节奏",
                    ),
                ),
                (
                    "preferred_style",
                    models.CharField(
                        choices=[
                            ("visual", "视觉型"),
                            ("auditory", "听觉型"),
                            ("kinesthetic", "动手型"),
                            ("reading", "阅读型"),
                            ("mixed", "混合型"),
                        ],
                        default="mixed",
                        max_length=20,
                        verbose_name="偏好学习风格",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("friendly", "友好"),
                            ("professional", "专业"),
                            ("encouraging", "鼓励"),
                            ("casual", "随意"),
                            ("formal", "正式"),
                        ],
                        default="friendly",
                        max_length=20,
                        verbose_name="语调风格",
                    ),
                ),
                (
                    "feedback_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "即时反馈"),
                            ("lesson_end", "课程结束"),
                            ("daily", "每日"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                        ],
                        default="lesson_end",
                        max_length=20,
                        verbose_name="反馈频率",
                    ),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "高中"),
                            ("undergraduate", "本科"),
                            ("graduate", "研究生"),
                            ("phd", "博士"),
                            ("professional", "职业培训"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="教育水平",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="用户掌握的技能列表",
                        verbose_name="技能列表",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户设置",
                "verbose_name_plural": "用户设置",
                "db_table": "user_settings",
            },
        ),
    ]
