# Generated by Django 4.2.13 on 2025-08-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersession",
            options={"verbose_name": "用户会话", "verbose_name_plural": "用户会话"},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["last_login"], name="users_last_lo_65b80e_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["account_locked_until"], name="users_account_94b59b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email_verified"], name="users_email_v_0e5f70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["two_factor_enabled"], name="users_two_fac_74d74d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["user"], name="authenticat_user_id_43ea0f_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["token"], name="authenticat_token_06b861_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["created_at"], name="authenticat_created_406c61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["last_activity"], name="authenticat_last_ac_04a1e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["expires_at"], name="authenticat_expires_8c23d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_active"], name="authenticat_is_acti_46022b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["ip_address"], name="authenticat_ip_addr_d6bbd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_suspicious"], name="authenticat_is_susp_3c1499_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="authenticat_user_id_f427c8_idx"
            ),
        ),
    ]
